name: pr-checks
run-name: ${{ github.actor }} is checking the package size
on:
  pull_request:
    types: [opened, reopened]
jobs:
  package-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Package size report
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
